# Generated by Django 5.2.10 on 2026-01-21 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("AUDIENCE", "Audience / Plaidoirie"),
                            ("RDV", "Rendez-vous client"),
                            ("FORMALITE", "Formalité notariale"),
                            ("CONGE", "Congé / Absence"),
                            ("AUTRE", "Autre événement"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Type d'événement",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début"
                    ),
                ),
                (
                    "all_day",
                    models.BooleanField(default=True, verbose_name="Journée entière"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description / Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="dossiers.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement calendrier",
                "verbose_name_plural": "Événements calendrier",
                "ordering": ["-start_date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="agenda_even_start_d_c7bd52_idx"
                    ),
                    models.Index(fields=["type"], name="agenda_even_type_e33fb7_idx"),
                    models.Index(
                        fields=["dossier"], name="agenda_even_dossier_ec90e1_idx"
                    ),
                ],
            },
        ),
    ]
