# Generated by Django 5.2.10 on 2026-01-20 07:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur système"),
                            ("AVOCAT", "Avocat"),
                            ("NOTAIRE", "Notaire"),
                            ("CONSEIL_JURIDIQUE", "Conseil juridique"),
                            ("STAGIAIRE", "Stagiaire / Collaborateur"),
                            ("SECRETAIRE", "Secrétaire / Clerc"),
                            ("ASSISTANT", "Assistant juridique"),
                        ],
                        default="STAGIAIRE",
                        help_text="Détermine les permissions par défaut dans l'application",
                        max_length=20,
                        verbose_name="Rôle dans le cabinet",
                    ),
                ),
                (
                    "professional_id",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : BAR/GAB/2023/001 pour un avocat ou NOT/GAB/001 pour un notaire",
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro professionnel ne doit contenir que des lettres majuscules, chiffres, tirets ou slashes.",
                                regex="^[A-Z0-9/-]+$",
                            )
                        ],
                        verbose_name="Numéro de carte professionnelle",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format international ou local valide (8 à 15 chiffres).",
                                regex="^\\+?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Téléphone professionnel",
                    ),
                ),
                (
                    "has_accepted_privacy_policy",
                    models.BooleanField(
                        default=False,
                        help_text="Requis pour la conformité Loi 001/2011 modifiée 2023",
                        verbose_name="A accepté la politique de confidentialité",
                    ),
                ),
                (
                    "privacy_policy_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date d'acceptation de la politique de confidentialité",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver plutôt que supprimer pour conserver l'historique",
                        verbose_name="Compte actif",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at", "last_name", "first_name"],
                "permissions": [
                    (
                        "can_view_all_dossiers",
                        "Peut consulter tous les dossiers du cabinet",
                    ),
                    ("can_manage_users", "Peut gérer les comptes utilisateurs"),
                    ("can_export_data", "Peut exporter des données (RGPD)"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
