# Generated by Django 5.2.10 on 2026-01-20 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField(verbose_name="ID de l'objet")),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : [GAB-2026-0001] Succession M. X",
                        max_length=255,
                        verbose_name="Représentation de l'objet",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression définitive"),
                            ("VIEW", "Consultation (lecture)"),
                            ("DOWNLOAD", "Téléchargement de document"),
                            ("PRINT", "Impression (si implémenté)"),
                            ("SHARE", "Partage interne (assignation)"),
                            ("LOGIN", "Connexion réussie"),
                            ("LOGIN_FAILED", "Tentative de connexion échouée"),
                            ("LOGOUT", "Déconnexion"),
                            ("EXPORT", "Export de données (RGPD)"),
                            ("CONSENT", "Consentement RGPD accordé"),
                        ],
                        max_length=20,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Diff JSON : {'field': ['ancienne_valeur', 'nouvelle_valeur']}",
                        null=True,
                        verbose_name="Modifications apportées",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Commentaire ou justification"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="User-Agent navigateur"),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="URL de la requête"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Clé de session"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date et heure",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("can_view_audit_logs", "Peut consulter les logs d'audit"),
                    ("can_export_audit_logs", "Peut exporter les logs (RGPD)"),
                ],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["user"], name="audit_audit_user_id_292c79_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="audit_audit_action__dd3a3c_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_audit_timesta_19e18a_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_audit_ip_addr_685e3f_idx"
                    ),
                    models.Index(
                        fields=["request_path"], name="audit_audit_request_b920c5_idx"
                    ),
                ],
            },
        ),
    ]
