# Generated by Django 5.2.10 on 2026-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Clé de session"
            ),
        ),
    ]
