# Generated by Django 4.2.7 on 2026-01-25 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0002_alter_auditlog_session_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Entrée d'Audit",
                "verbose_name_plural": "Journal d'Audit",
            },
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_audit_user_id_292c79_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_audit_action__dd3a3c_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_audit_request_b920c5_idx",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="sensitive_fields_hash",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Hash des champs sensibles"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Création"),
                    ("READ", "Lecture"),
                    ("UPDATE", "Modification"),
                    ("DELETE", "Suppression"),
                    ("DOWNLOAD", "Téléchargement"),
                    ("UPLOAD", "Upload"),
                    ("RESTORE", "Restauration"),
                    ("INTEGRITY_CHECK", "Vérification Intégrité"),
                    ("INTEGRITY_FAILURE", "Échec Intégrité"),
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("LOGIN_FAILED", "Échec Connexion"),
                    ("PERMISSION_DENIED", "Accès Refusé"),
                ],
                max_length=20,
                verbose_name="Type d'action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Données sensibles automatiquement anonymisées",
                verbose_name="Changements",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(max_length=255, verbose_name="Représentation"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Chemin requête"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Clé de session"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="User Agent"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "timestamp"], name="audit_audit_user_id_e8be02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="audit_audit_action__74f5dd_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_auditlog",
        ),
    ]
