# Generated by Django 4.2.7 on 2026-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Création"),
                    ("READ", "Lecture"),
                    ("UPDATE", "Modification"),
                    ("DELETE", "Suppression"),
                    ("DOWNLOAD", "Téléchargement"),
                    ("UPLOAD", "Upload"),
                    ("RESTORE", "Restauration"),
                    ("INTEGRITY_CHECK", "Vérification Intégrité"),
                    ("INTEGRITY_FAILURE", "Échec Intégrité"),
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("LOGIN_FAILED", "Échec Connexion"),
                    ("PERMISSION_DENIED", "Accès Refusé"),
                    ("CONSENT", "Consentement"),
                ],
                max_length=20,
                verbose_name="Type d'action",
            ),
        ),
    ]
