# Generated by Django 5.2.10 on 2026-01-20 07:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="Intitulé du dossier"
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        editable=False,
                        help_text="Générée automatiquement : GAB-YYYY-NNNN",
                        max_length=30,
                        unique=True,
                        verbose_name="Référence interne",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "CONTENTIEUX",
                                "Contentieux (civil, pénal, administratif)",
                            ),
                            ("CONSEIL", "Conseil juridique / Avis"),
                            ("RECOUVREMENT", "Recouvrement de créances"),
                            ("TRAVAIL", "Droit du travail"),
                            ("IMMOBILIER", "Actes immobiliers / Foncier"),
                            ("SUCCESSION", "Succession / Partage"),
                            ("MARIAGE", "Contrat de mariage / Régime matrimonial"),
                            ("DONATION", "Donation / Libéralité"),
                            ("SOCIETE", "Constitution / Modification société OHADA"),
                            ("FAMILLE", "Divorce, garde, filiation"),
                            ("COMMERCIAL", "Droit commercial OHADA"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert / En cours"),
                            ("ATTENTE", "En attente de pièces ou décision"),
                            ("SUSPENDU", "Suspendu"),
                            ("CLOTURE", "Clôturé"),
                            ("ARCHIVE", "Archivé"),
                        ],
                        default="OUVERT",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Résumé et notes confidentielles"
                    ),
                ),
                (
                    "opponent",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Partie adverse / Opposant",
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Juridiction / Tribunal / Office notarial",
                    ),
                ),
                (
                    "critical_deadline",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Délai critique / Audience / Formalité",
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Exécution mandat, obligation légale, intérêt légitime",
                        max_length=255,
                        verbose_name="Base légale du traitement",
                    ),
                ),
                (
                    "retention_period_years",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Illimitée pour actes notariés authentiques",
                        verbose_name="Durée de conservation (années)",
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'ouverture",
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                (
                    "archived_date",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clercs, stagiaires ou collaborateurs ayant accès au dossier",
                        related_name="accessible_dossiers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs autorisés",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        limit_choices_to={
                            "role__in": ["AVOCAT", "NOTAIRE", "CONSEIL_JURIDIQUE"]
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_dossiers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable principal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "ordering": ["-opening_date", "-created_at"],
                "permissions": [
                    (
                        "can_view_confidential_dossier",
                        "Peut consulter les dossiers confidentiels",
                    ),
                    ("can_archive_dossier", "Peut archiver un dossier"),
                ],
                "indexes": [
                    models.Index(
                        fields=["reference_code"], name="dossiers_do_referen_927f6f_idx"
                    ),
                    models.Index(
                        fields=["client"], name="dossiers_do_client__4f1506_idx"
                    ),
                    models.Index(
                        fields=["responsible"], name="dossiers_do_respons_32ec7a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="dossiers_do_status_f35af7_idx"
                    ),
                    models.Index(
                        fields=["category"], name="dossiers_do_categor_103237_idx"
                    ),
                    models.Index(
                        fields=["critical_deadline"],
                        name="dossiers_do_critica_01e771_idx",
                    ),
                    models.Index(
                        fields=["opening_date"], name="dossiers_do_opening_4b932d_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            ("closing_date__gte", models.F("opening_date")),
                            ("closing_date__isnull", True),
                            _connector="OR",
                        ),
                        name="closing_date_after_opening",
                    )
                ],
            },
        ),
    ]
