# Generated by Django 4.2.7 on 2026-01-26 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dossier",
            options={
                "ordering": ["-opening_date", "-created_at"],
                "permissions": [
                    (
                        "can_view_confidential_dossier",
                        "Peut consulter les dossiers confidentiels",
                    ),
                    ("can_archive_dossier", "Peut archiver un dossier"),
                    (
                        "assign_users_dossier",
                        "Peut assigner des collaborateurs au dossier",
                    ),
                    ("view_all_dossiers", "Peut voir tous les dossiers du cabinet"),
                    (
                        "manage_dossier_permissions",
                        "Peut gérer les permissions d'un dossier",
                    ),
                ],
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
            },
        ),
    ]
