# Generated by Django 5.2.10 on 2026-01-20 07:22

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("PHYSIQUE", "Personne Physique"),
                            ("MORALE", "Personne Morale"),
                        ],
                        default="PHYSIQUE",
                        max_length=10,
                        verbose_name="Type de client",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Prénom(s)"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "ni_number",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : 123456789 pour CNI gabonaise",
                        max_length=50,
                        verbose_name="N° pièce d'identité (CNI / Passeport)",
                    ),
                ),
                (
                    "ni_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CNI", "Carte Nationale d'Identité"),
                            ("PASSPORT", "Passeport"),
                        ],
                        max_length=20,
                        verbose_name="Type de pièce",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Raison sociale"
                    ),
                ),
                (
                    "rccm",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format RCCM attendu : ex. LBV/2023/A/12345",
                                regex="^[A-Z]{3}/\\d{4}/[A-Z]/\\d+$",
                            )
                        ],
                        verbose_name="N° RCCM",
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le NIF gabonais doit comporter exactement 10 chiffres.",
                                regex="^\\d{10}$",
                            )
                        ],
                        verbose_name="NIF / Identifiant Fiscal Unique",
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nom du représentant légal",
                    ),
                ),
                (
                    "representative_role",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Fonction du représentant",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Adresse email principale",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        help_text="Ex. : +241 01 23 45 67",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide.",
                                regex="^\\+?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Téléphone principal",
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide.",
                                regex="^\\+?\\d{8,15}$",
                            )
                        ],
                        verbose_name="Téléphone secondaire",
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Rue / BP"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Glass, Louis, Akébé, Nkembo",
                        max_length=100,
                        verbose_name="Quartier",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Libreville", max_length=100, verbose_name="Ville"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Gabon", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Fournies par le client, acte notarié, jugement...",
                        max_length=255,
                        verbose_name="Source des données",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Coché si le client a été informé et a consenti au traitement",
                        verbose_name="Consentement RGPD obtenu",
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du consentement"
                    ),
                ),
                (
                    "retention_period_years",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Au-delà : archivage ou anonymisation. Illimité pour actes notariés.",
                        verbose_name="Durée de conservation (années)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Client actif"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Notes internes (confidentielles)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="clients_cli_last_na_198e2f_idx",
                    ),
                    models.Index(
                        fields=["company_name"], name="clients_cli_company_9dfa94_idx"
                    ),
                    models.Index(fields=["nif"], name="clients_cli_nif_e3c63a_idx"),
                    models.Index(fields=["rccm"], name="clients_cli_rccm_e5c8fa_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("client_type", "PHYSIQUE")),
                        fields=("ni_number", "ni_type"),
                        name="unique_ni_per_individual",
                    )
                ],
            },
        ),
    ]
