# Generated by Django 4.2.7 on 2026-01-25 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_secondary",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro de téléphone invalide.", regex="^\\+?\\d{8,15}$"
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
    ]
