# Generated by Django 4.2.7 on 2026-01-25 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_phone_secondary_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le NIF gabonais doit comporter exactement 10 chiffres.",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="NIF / Identifiant Fiscal Unique",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="rccm",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format RCCM attendu : ex. LBV/2023/A/12345",
                        regex="^[A-Z]{3}/\\d{4}/[A-Z]/\\d+$",
                    )
                ],
                verbose_name="N° RCCM",
            ),
        ),
    ]
