# Generated by Django 4.2.7 on 2026-01-25 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_rccm_nif_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le NIF gabonais doit suivre le format XXXXXX-L (ex: 370669-C)",
                        regex="^\\d{6}-[A-Z]$",
                    )
                ],
                verbose_name="NIF / Identifiant Fiscal Unique",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="rccm",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Format RCCM OHADA attendu : ex. GA-LBV-2024-A12-00567",
                        regex="^GA-[A-Z]{3}-\\d{4}-[A-Z]\\d{2}-\\d{5}$",
                    )
                ],
                verbose_name="N° RCCM",
            ),
        ),
    ]
