# Generated by Django 4.2.7 on 2026-02-06 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_update_rccm_nif_validators_gabon"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="client",
            name="unique_ni_per_individual",
        ),
        migrations.AlterField(
            model_name="client",
            name="ni_number",
            field=models.CharField(
                blank=True,
                help_text="Ex. : 123456789 pour CNI gabonaise",
                max_length=50,
                null=True,
                verbose_name="N° pièce d'identité (CNI / Passeport)",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="ni_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CNI", "Carte Nationale d'Identité"),
                    ("PASSPORT", "Passeport"),
                    ("RESIDENCE_PERMIT", "Permis de séjour"),
                    ("OTHER", "Autre"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type de pièce",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nif",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le NIF gabonais doit suivre le format XXXXXXL ou XXXXXX-L (ex: 370669C ou 370669-C)",
                        regex="^\\d{6}-?[A-Z]$",
                    )
                ],
                verbose_name="NIF / Identifiant Fiscal Unique",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_primary",
            field=models.CharField(
                help_text="Ex. : +241 01 23 45 67",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro de téléphone invalide.",
                        regex="^\\+?[\\d\\s\\-]{8,20}$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_secondary",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro de téléphone invalide.",
                        regex="^\\+?[\\d\\s\\-]{8,20}$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("client_type", "PHYSIQUE"), ("ni_number__isnull", False)
                ),
                fields=("ni_number", "ni_type"),
                name="unique_ni_per_individual",
            ),
        ),
    ]
