# Generated by Django 4.2.7 on 2026-01-25 15:27

import apps.documents.models
import apps.documents.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="Modifié le",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver au lieu de supprimer (soft-delete)",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom du dossier"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="dossiers.dossier",
                        verbose_name="Dossier juridique",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="documents.folder",
                        verbose_name="Dossier parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier",
                "verbose_name_plural": "Dossiers",
                "db_table": "documents_folder",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de création",
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver au lieu de supprimer (soft-delete)",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=apps.documents.storage.AuditedFileStorage(),
                        upload_to=apps.documents.models.secure_document_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nom original"),
                ),
                (
                    "file_extension",
                    models.CharField(max_length=10, verbose_name="Extension"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="Taille (octets)")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="Type MIME"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        help_text="Empreinte cryptographique garantissant l'intégrité",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash SHA-256",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Numéro de version"
                    ),
                ),
                (
                    "is_current_version",
                    models.BooleanField(
                        default=True,
                        help_text="True uniquement pour la dernière version",
                        verbose_name="Version actuelle",
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Usage Interne"),
                            ("confidential", "Confidentiel"),
                            ("secret", "Secret Professionnel"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="Niveau de sensibilité",
                    ),
                ),
                (
                    "retention_until",
                    models.DateField(
                        blank=True,
                        help_text="Date de suppression automatique (RGPD)",
                        null=True,
                        verbose_name="Conservation jusqu'au",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dossiers.dossier",
                        verbose_name="Dossier juridique",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.folder",
                        verbose_name="Sous-dossier",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_versions",
                        to="documents.document",
                        verbose_name="Version précédente",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents_document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.CheckConstraint(
                check=models.Q(("id", models.F("parent_id")), _negated=True),
                name="folder_no_self_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["dossier", "is_current_version"],
                name="documents_d_dossier_739670_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_hash"], name="documents_d_file_ha_a7f76e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_at"], name="documents_d_uploade_65506e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["original_filename"], name="documents_d_origina_0f3879_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current_version", True)),
                fields=("dossier", "original_filename"),
                name="unique_current_version_per_dossier",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("previous_version__isnull", True), ("version", 1)),
                    models.Q(("previous_version__isnull", False), ("version__gt", 1)),
                    _connector="OR",
                ),
                name="version_integrity_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_current_version", False),
                    models.Q(
                        ("is_current_version", True),
                        ("previous_version__isnull", True),
                        ("version", 1),
                    ),
                    models.Q(
                        ("is_current_version", True),
                        ("previous_version__isnull", False),
                        ("version__gt", 1),
                    ),
                    _connector="OR",
                ),
                name="current_version_must_have_history",
            ),
        ),
    ]
