# Generated by Django 5.2.10 on 2026-01-20 07:22

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nom du répertoire"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="documents.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Répertoire virtuel",
                "verbose_name_plural": "Répertoires virtuels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.documents.models.secure_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                    "rtf",
                                    "msg",
                                    "eml",
                                    "zip",
                                ]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Titre du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description / Notes"),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom original"
                    ),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, editable=False, max_length=10),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille (octets)"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_current_version",
                    models.BooleanField(default=True, verbose_name="Version actuelle"),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("CONFIDENTIEL", "Confidentiel"),
                            (
                                "TRES_CONFIDENTIEL",
                                "Très confidentiel (secret professionnel renforcé)",
                            ),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Niveau de confidentialité",
                    ),
                ),
                (
                    "retention_until",
                    models.DateField(
                        blank=True,
                        help_text="Au-delà : archivage ou destruction sécurisée",
                        null=True,
                        verbose_name="Date de fin de conservation légale",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de téléversement",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="dossiers.dossier",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Téléversé par",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.folder",
                        verbose_name="Répertoire virtuel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at", "title"],
                "permissions": [
                    (
                        "can_view_confidential_docs",
                        "Peut consulter les documents confidentiels",
                    ),
                    (
                        "can_delete_documents",
                        "Peut supprimer définitivement des documents",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["dossier", "parent"], name="documents_f_dossier_90c210_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("name", "dossier", "parent")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["dossier", "folder"], name="documents_d_dossier_c713e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["title"], name="documents_d_title_ccf306_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_at"], name="documents_d_uploade_65506e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["sensitivity"], name="documents_d_sensiti_2ce612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["file_extension"], name="documents_d_file_ex_bb4200_idx"
            ),
        ),
    ]
